---
- name: download Dokku installation script
  get_url:
    url:  "{{ url }}"
    dest: "{{ tmp_file }}"
    mode: 0755

- name:    install Dokku itself
  command: "{{ tmp_file }}"
  args:
    creates: "{{ dokku_home }}"
  environment:
    DOKKU_TAG: "{{ tag }}"
