---
- hosts:        all
  become:       yes
  gather_facts: no
  pre_tasks:
    - include: ../tasks/install-python.yml

- hosts:        all
  gather_facts: yes
  become:       yes
  vars_files:
    - ../data.yml
  roles:
    - ../roles/utils
    - ../roles/git
    - ../roles/machine-user
    - ../roles/authorize-access
    - ../roles/dokku
